#!/usr/bin/env bash
set -euo pipefail

SAMPLE_ID=${1:?Usage: $0 sample0|sample1|sample2|sample3|sample4|sample5}
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FULL26_ROOT="${FULL26_ROOT:-/path/to/storage/datasets/robotics/RoboMemArena/derived/retrieval_full26_tdense5/predimem_2048_fp32}"

case "${SAMPLE_ID}" in
  sample0) RESCUE=0; RESCUE_CONFIRM=2; RESCUE_MARGIN=0.05; REINFORCEMENTS=3 ;;
  sample1) RESCUE=1; RESCUE_CONFIRM=3; RESCUE_MARGIN=0.08; REINFORCEMENTS=3 ;;
  sample2) RESCUE=1; RESCUE_CONFIRM=2; RESCUE_MARGIN=0.05; REINFORCEMENTS=3 ;;
  sample3) RESCUE=1; RESCUE_CONFIRM=1; RESCUE_MARGIN=0.08; REINFORCEMENTS=3 ;;
  sample4) RESCUE=1; RESCUE_CONFIRM=2; RESCUE_MARGIN=0.03; REINFORCEMENTS=4 ;;
  sample5) RESCUE=1; RESCUE_CONFIRM=1; RESCUE_MARGIN=0.03; REINFORCEMENTS=4 ;;
  *) echo "Unknown sample: ${SAMPLE_ID}" >&2; exit 2 ;;
esac

export TASK_IDS="${TASK_IDS:-6,7,8,9,10,15,16}"
export MEMORY_ALLOWED_TASK_IDS="${MEMORY_ALLOWED_TASK_IDS:-6,7,8,9,10,15,16}"
export UPPER_GUIDANCE_ALLOWED_TASK_IDS="${UPPER_GUIDANCE_ALLOWED_TASK_IDS:-6,7,8,9,10,15,16}"
export EPISODES_PER_TASK="${EPISODES_PER_TASK:-10}"
export SEED="${SEED:-50}"
export UPPER_BATCH_SIZE="${UPPER_BATCH_SIZE:-32}"
export LOWER_BATCH_SIZE="${LOWER_BATCH_SIZE:-32}"
export ENV_WORKERS="${ENV_WORKERS:-32}"
export SAVE_VIDEO="${SAVE_VIDEO:-0}"
export RECORD_MEMORY_DATA=0

export UPPER_GUIDANCE_FEEDBACK_MODE=control
export UPPER_GUIDANCE_FEEDBACK_HORIZON=6
export UPPER_GUIDANCE_FEEDBACK_CONFIRMATIONS=2
export UPPER_GUIDANCE_FEEDBACK_SIMILARITY_TOLERANCE=0.02
export UPPER_GUIDANCE_FEEDBACK_PURITY_TOLERANCE=0.10
export UPPER_GUIDANCE_FEEDBACK_MAX_REINFORCEMENTS="${REINFORCEMENTS}"
export UPPER_GUIDANCE_FEEDBACK_LOWER_RESCUE_ENABLED="${RESCUE}"
export UPPER_GUIDANCE_FEEDBACK_LOWER_RESCUE_CONFIRMATIONS="${RESCUE_CONFIRM}"
export UPPER_GUIDANCE_FEEDBACK_LOWER_RESCUE_MIN_MARGIN="${RESCUE_MARGIN}"

RUN_NAME="${SAMPLE_ID}_rescue${RESCUE}_c${RESCUE_CONFIRM}_m${RESCUE_MARGIN}_r${REINFORCEMENTS}_seed${SEED}"
export RUN_ROOT="${RUN_ROOT:-${FULL26_ROOT}/eval/lower_rescue_round1/${RUN_NAME}}"
exec bash "${ROOT}/scripts/robomemarena/run_predimem_counting_history_knn_self.sh" fusion_fusion_action
